---
# Modified from https://github.com/microservices-demo/microservices-demo
# Please see this repository for the original

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: session-db
  labels:
    name: session-db
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: session-db
    spec:
      containers:
      - name: session-db
        image: redis:alpine
        ports:
        - name: redis
          containerPort: 6379
